name: jlonevae
channels:
  - anaconda
  - pytorch
  - defaults
dependencies:
  - python>=3.6,<3.7
  - tensorboard==2.1.0
  - tensorflow-gpu=2.1.0
  - cudatoolkit=10.1
  - pip==20.2.4
  - pytorch=1.7.1
  - matplotlib
  - numpy 
  - opencv
  - opt_einsum
  - jupyterlab
  - scipy
  - scikit-learn
  - pillow
  - absl-py==0.7.1
  - astor==0.7.1
  - cloudpickle==1.6.0
  - dill==0.3.3
  - enum34==1.1.10
  - future==0.18.2
  - gast==0.2.2
  - imageio==2.9.0
  - llvmlite==0.36.0
  - mock==4.0.3
  - numba==0.53.1
  - pandas==1.1.5
  - protobuf==3.8.0
  - pytz==2021.1
  - requests-toolbelt==0.9.1
  - scipy==1.4.1
  - seaborn==0.11.1
  - simplejson==3.17.2
  - pip:
    - tensorflow-addons==0.13.0
    - typeguard==2.12.0
    - dm-tree==0.1.6
    - tensorflow-hub==0.12.0
    - redis==3.5.3
    - python-gitlab==2.7.1
    - gin-config==0.4.0
    - tensorflow-probability==0.9.0
